apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    k8s-app: sample01
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    k8s-app: sample01