apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service-bus-orders
spec:
  secretTargetRef:
    - parameter: connection
      name: secrets-order-management
      key: servicebus-order-management-connectionstring
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-order-management
  labels:
    app: order-processor
data:
  servicebus-order-management-connectionstring: <COLOCA_TU_CADENA_DE_AZURE_SERVICE_BUS_AQUI_EN_BASE64>
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: order-processor-scaler
  labels:
    app: order-processor
    deploymentName: order-processor
spec:
  scaleTargetRef:
    deploymentName: order-processor
  minReplicaCount: 0
  maxReplicaCount: 6
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: orders
        queueLength: "5"
      authenticationRef:
        name: trigger-auth-service-bus-orders
